
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

recorder:
  purge_keep_days: 1095

input_number:
  box1:
    name: Minimale Stromerzeugung
    initial: 300
    min: 0
    max: 99999999
    step: 1
    mode: box
    unit_of_measurement: W
    icon: mdi:solar-panel-large

  box2:
    name: Periode der Überprüfung
    initial: 5
    min: 0
    max: 99999999
    step: 1
    mode: box
    unit_of_measurement: Min
    icon: mdi:av-timer

  box3:
    name: Maximale Laufzeit Heizung
    initial: 120
    min: 0
    max: 99999999
    step: 1
    mode: box
    unit_of_measurement: Min
    icon: mdi:av-timer

  box4:
    name: Abkühldauer
    initial: 15
    min: 0
    max: 99999999
    step: 1
    mode: box
    unit_of_measurement: Min
    icon: mdi:av-timer

  box5:
    name: Unteres Temperaturlimit Heizung
    initial: 19
    min: 0
    max: 99999999
    step: 1
    mode: box
    unit_of_measurement: °C
    icon: mdi:home-thermometer-outline

  box6:
    name: Unteres Luftfeuchtigkeitslimit Heizung
    initial: 70
    min: 0
    max: 99999999
    step: 1
    mode: box
    unit_of_measurement: "%"
    icon: mdi:water-percent

  box7:
    name: Oberes Temperaturlimit Heizung
    initial: 21
    min: 0
    max: 99999999
    step: 1
    mode: box
    unit_of_measurement: °C
    icon: mdi:home-thermometer-outline

  box8:
    name: Oberes Luftfeuchtigkeitslimit Heizung
    initial: 75
    min: 0
    max: 99999999
    step: 1
    mode: box
    unit_of_measurement: "%"
    icon: mdi:water-percent

  box9:
    name: Stromerzeugung Boiler
    initial: 400
    min: 0
    max: 99999999
    step: 1
    mode: box
    unit_of_measurement: "W"
    icon: mdi:solar-panel-large
