- id: '1700510666034'
  alias: Überhitzungsschutz
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.shellyswitch25_b94fa2_channel_1_power
    from: '0.0'
    for:
      minutes: '{{ states(''input_number.box3'') }}

        '
  condition: []
  action:
  - service: automation.turn_off
    data:
      stop_actions: true
    target:
      entity_id:
      - automation.stromerzeugungsprufung_standard
      - automation.stromerzeugungsprufung_smart
  - type: turn_off
    device_id: 6a8881d9cab80f94d13b08e0613a4ac2
    entity_id: 45c0e1d22ddad70910b698cbb6067cca
    domain: switch
  - delay:
      hours: 0
      minutes: '{{ states(''input_number.box4'') }}

        '
      seconds: 0
      milliseconds: 0
  - service: automation.turn_on
    data: {}
    target:
      entity_id:
      - automation.stromerzeugungsprufung_smart
      - automation.stromerzeugungsprufung_standard
  mode: single
- id: '1703066270644'
  alias: Stromerzeugungsprüfung Smart
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /1
  condition:
  - condition: template
    value_template: '{{ now().minute % states(''input_number.box2'')|int == 0 }}

      '
  - condition: state
    entity_id: input_boolean.smarte_heizungssteuerung
    state: 'on'
  action:
  - if:
    - condition: numeric_state
      entity_id: sensor.shellyswitch25_b94fa2_channel_2_power
      above: input_number.box1
    then:
    - if:
      - condition: or
        conditions:
        - condition: numeric_state
          entity_id: sensor.temperatur
          below: input_number.box5
        - condition: numeric_state
          entity_id: sensor.luftfeuchtigkeit
          above: input_number.box8
      then:
      - type: turn_on
        device_id: 6a8881d9cab80f94d13b08e0613a4ac2
        entity_id: 45c0e1d22ddad70910b698cbb6067cca
        domain: switch
      else:
      - if:
        - condition: and
          conditions:
          - condition: numeric_state
            entity_id: sensor.temperatur
            above: input_number.box7
          - condition: numeric_state
            entity_id: sensor.luftfeuchtigkeit
            below: input_number.box6
        then:
        - type: turn_off
          device_id: 6a8881d9cab80f94d13b08e0613a4ac2
          entity_id: 45c0e1d22ddad70910b698cbb6067cca
          domain: switch
    else:
    - type: turn_off
      device_id: 6a8881d9cab80f94d13b08e0613a4ac2
      entity_id: 45c0e1d22ddad70910b698cbb6067cca
      domain: switch
  mode: single
- id: '1703067993308'
  alias: Stromerzeugungsprüfung - Standard
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /1
  condition:
  - condition: template
    value_template: '{{ now().minute % states(''input_number.box2'')|int == 0 }}

      '
  - condition: state
    entity_id: input_boolean.smarte_heizungssteuerung
    state: 'off'
  action:
  - if:
    - condition: numeric_state
      entity_id: sensor.shellyswitch25_b94fa2_channel_2_power
      above: input_number.box1
    then:
    - type: turn_on
      device_id: 6a8881d9cab80f94d13b08e0613a4ac2
      entity_id: 45c0e1d22ddad70910b698cbb6067cca
      domain: switch
    else:
    - type: turn_off
      device_id: 6a8881d9cab80f94d13b08e0613a4ac2
      entity_id: 45c0e1d22ddad70910b698cbb6067cca
      domain: switch
  mode: single
